# Generated by Django 5.0.6 on 2024-05-19 16:44

import django.utils.timezone
from django.db import migrations, models
from django.db.models  import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='description',
            field=JSONField(),
            preserve_default=False,
        ),
    ]
