# Generated by Django 5.0.6 on 2024-05-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_damage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='item',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='location',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sub_group',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='creator',
        ),
    ]
